# Generated by Django 6.0.2 on 2026-02-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text="e.g., 'heart', 'home', 'school'", max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbs/')),
                ('video_url', models.URLField(blank=True, help_text='Link to YouTube/Vimeo if not uploading file')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in the large hero box?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('category', models.CharField(choices=[('CORPORATE', 'Corporate Partner'), ('NGO', 'NGO Ally'), ('GOVT', 'Government Agency')], max_length=20)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('website_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('LEADERSHIP', 'Leadership'), ('CORE', 'Core Staff'), ('VOLUNTEER', 'Volunteer')], default='CORE', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('initials', models.CharField(help_text="Used if no image exists (e.g., 'EM')", max_length=2)),
            ],
        ),
    ]
