# Generated by Django 6.0.2 on 2026-03-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in the large yellow box?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='SMILE AGAIN', help_text='Use <br> for line breaks', max_length=200)),
                ('hero_description', models.TextField(default='Empowering individuals with disabilities...')),
                ('mission_text', models.TextField(blank=True)),
                ('vision_text', models.TextField(blank=True)),
                ('lives_impacted', models.CharField(default='10K+', max_length=20)),
                ('programs_count', models.CharField(default='50+', max_length=20)),
                ('countries_count', models.CharField(default='25+', max_length=20)),
            ],
            options={
                'verbose_name': 'Home Global Setting',
                'verbose_name_plural': 'Home Global Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji or Icon Name', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program_tag', models.CharField(help_text='e.g. Education Access', max_length=100)),
                ('quote', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='initials',
            field=models.CharField(max_length=2),
        ),
    ]
