# Generated by Django 6.0.2 on 2026-03-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0003_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.CharField(max_length=50)),
                ('donation_type', models.CharField(choices=[('ONE-TIME', 'One-Time'), ('MONTHLY', 'Monthly')], default='ONE-TIME', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
